animal = input("Enter an animal: ")
place = input("Enter a place: ")
action = input("Enter a verb (action): ")
adjective = input("Enter an adjective: ")
number = input("Enter a number: ")

print()
print(f"Once upon a time, a {animal} decided to visit the {place}.")
print(f"It was feeling very {adjective} and wanted to {action} with anyone it met.")
print(f"After {number} tries, the {animal} finally made a new friend and they laughed together.")
print("And they lived happily ever after in the most unexpected place.")
